language: clojure
lein: lein
sudo: false

addons:
  postgresql: 9.3

services:
  - postgresql

before_script:
  - createdb test

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - lein test-all

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
