language: clojure
lein: lein2

addons:
  postgresql: 9.3

services:
  - postgresql

before_script:
  - createdb test

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
